1:
	gcc -Wall -g -std=c99 -Werror -pthread 1.c -o 1
2:
	gcc -Wall -g -std=c99 -Werror -pthread 2.c -o 2
3:
	gcc -Wall -g -std=c99 -Werror -pthread 3.c -o 3
4:
	gcc -Wall -g -std=c99 -Werror -pthread 4.c -o 4
5:
	g++ -Wall -std=c++11 -Werror -pthread 5.cpp -o 5
6:
	g++ -Wall -std=c++11 -Werror -pthread 6.cpp -o 6	
7:
	g++ -Wall -std=c++11 -Werror -pthread 7.cpp -o 7	
8:
	g++ -Wall -std=c++11 -Werror -pthread 8.cpp -o 8	
9:
	g++ -Wall -std=c++11 -Werror -pthread 9.cpp -o 9
10:
	g++ -Wall -std=c++11 -Werror -pthread 10.cpp -o 10
11:
	g++ -Wall -std=c++11 -Werror -pthread 11.cpp -o 11
12:
	g++ -Wall -std=c++11 -Werror -pthread 12.cpp -o 12
clean:
	rm -f 1.exe
	rm -f 2.exe
	rm -f 3.exe
	rm -f 4.exe
	rm -f 5.exe
	rm -f 6.exe
	rm -f 7.exe
	rm -f 8.exe
	rm -f 9.exe
	rm -f 10.exe
	rm -f 11.exe
	rm -f 12.exe