1:
	gcc -Wall -g -std=c99 -Werror -pthread 1.c -o 1
2:
	gcc -Wall -g -std=c99 -Werror -pthread 2.c -o 2
3:
	gcc -Wall -g -std=c99 -Werror -pthread 3.c -o 3
4:
	gcc -Wall -g -std=c99 -Werror -pthread 4.c -o 4
clean:
	rm -f 1.exe
	rm -f 2.exe
	rm -f 3.exe
	rm -f 4.exe